[fusiondata]
git-tree-sha1 = "aca13f38b891ad1a149fb74e474bfd6836e1c803"

    [[fusiondata.download]]
    sha256 = "d0e04249578b564fe8622cb173d7bd8052b8b75bb8c345894bfde46ff399ad47"
    url = "https://github.com/QuantumKitHub/CategoryData.jl/archive/refs/tags/data-temp.tar.gz"
