name: FormatCheck

on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'release-'
    tags: '*'
  pull_request:
    branches:
      - 'main'
      - 'master'

jobs:
  formatcheck:
    name: "Format Check"
    uses: "QuantumKitHub/QuantumKitHubActions/.github/workflows/FormatCheck.yml@main"